import "../styles/globals.css";
import Head from "next/head";

import Header from "../components/Header";
import Footer from "../components/Footer";
import { Provider } from "react-redux";
import { persistor, store } from "../src/app/store";
import { Toaster } from "react-hot-toast";
import { PersistGate } from "redux-persist/integration/react";

import { BackToTop } from "../components";
import { BsArrowUp } from "react-icons/bs";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Nike Store Build</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/logo.svg" />
      </Head>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <Header />
          <Component {...pageProps} />
          <Toaster />
          <BackToTop Icon={BsArrowUp} />
          <Footer />
        </PersistGate>
      </Provider>
    </>
  );
}
